helm-extra-args: --timeout 600
check-version-increment: false
debug: true
chart-repos:
  - klausmeyer=https://klausmeyer.github.io/helm-charts
  - groundhog2k=https://groundhog2k.github.io/helm-charts
