rails-application:
  name: docker-registry-browser
  version: latest

  image:
    repository: klausmeyer/docker-registry-browser

  environment:
    # sealedSecrets: false
    plain: {}
    #  ANYTHING: "ANYTHING"
    secret: {}
    #  ANYTHING: "ANYTHING"

  deployments:
    web:
      enabled: true
      livenessProbe:
        httpGet:
          path: /ping
          port: http
      readinessProbe:
        httpGet:
          path: /ping
          port: http
