apiVersion: v2
name: release-tracker
description: A Helm chart for Kubernetes
type: application
version: "0.1.0"

dependencies:
  - name: rails-application
    version: "0.1.0"
    repository: https://klausmeyer.github.io/helm-charts

  - name: redis
    version: "2.1.3"
    repository: https://groundhog2k.github.io/helm-charts
