apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rails-application.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "rails-application.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.environment.plain }}
  {{ $key }}: {{ $value | quote }}
{{- end -}}
