{{ if .Values.environment.sealedSecrets }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "rails-application.fullname" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  labels:
    {{- include "rails-application.labels" . | nindent 4 }}
spec:
  encryptedData:
    {{- range $key, $value := .Values.environment.secret }}
    {{ $key }}: {{ $value | quote }}
{{- end -}}
{{ else }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rails-application.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "rails-application.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.environment.secret }}
  {{ $key }}: {{ $value | b64enc | quote }}
{{- end -}}
{{ end }}
