rails-application:
  name: whatchy
  version: "0.1.2"

  image:
    repository: klausmeyer/whatchy

  environment:
    # sealedSecrets: false
    plain: {}
      # AIRBRAKE_HOST: "<...>"
      # AIRBRAKE_PROJECT_ID: "<...>"
      # BANNER_CACHE_HOST: "<...>"
      # DOMAIN: "<...>"
      # S3_BUCKET: "<...>"
      # S3_ENDPOINT: "<...>"
      # S3_REGION: "<...>"
      # SMTP_ENABLED: "<...>"
      # SMTP_PORT: "<...>"
      # SMTP_SERVER: "<...>"
    secret: {}
      # AIRBRAKE_API_KEY: <...>
      # DATABASE_URL: "<...>"
      # S3_ACCESS_KEY_ID: "<...>"
      # S3_SECRET_ACCESS_KEY: "<...>"
      # SECRET_KEY_BASE: "<...>"
      # SMTP_PASSWORD: "<...>"
      # SMTP_USERNAME: "<...>"
      # THETVDB_APIKEY: "<...>"

  deployments:
    web:
      enabled: true

  cronjobs:
    daily:
      schedule: "30 6 * * *"
      args: ["rake", "crons:daily"]

redis:
  haMode:
    enabled: false
