name: Lint test charts

## Lint helm chart on every pull requests
on:
  pull_request:
    paths:
      - 'charts/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Fetch history
        run: git fetch --prune --unshallow

      - name: Set up Helm
        uses: azure/setup-helm@v4

      - uses: actions/setup-python@v6

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.7.0

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --target-branch ${{ github.event.repository.default_branch }})
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Run chart-testing (lint)
        if: steps.list-changed.outputs.changed == 'true'
        run: |
          ct lint \
            --target-branch ${{ github.event.repository.default_branch }} \
            --helm-extra-args="--timeout 600" \
            --check-version-increment=false \
            --validate-maintainers=false \
            --debug=true \
            --chart-repos="klausmeyer=https://klausmeyer.github.io/helm-charts,groundhog2k=https://groundhog2k.github.io/helm-charts"
